#!/bin/bash

# Start the service
echo -e "\tMagePanel installed successfully! Starting service.."
update-rc.d magepanel defaults
service magepanel start

echo -e "\tGive MagePanel about 3 minutes to initialize (installing Chrome for browser side)"
rm -f /tmp/hnc.log /tmp/hnc.err
nohup /opt/magepanel/install-chrome.sh > /tmp/hnc.log 2> /tmp/hnc.err &
