#!/bin/bash
# Start the services!

service magepanel start
echo "Give MagePanel about 3 minutes to initialize (installing Chrome for browser side)"
rm -f /tmp/hnc.log /tmp/hnc.err
nohup /opt/magepanel/install-chrome.sh > /tmp/hnc.log 2> /tmp/hnc.err &
