#!/bin/bash

# Start the services!
echo -e "\tMagePanel installed successfully! Starting service.."
#chmod +x /opt/magepanel/init-server.sh
#service magepanel start
magepanel start

echo -e "\tGive MagePanel about 3 minutes to initialize (installing Chrome for browser side)"
rm -f /tmp/hnc.log /tmp/hnc.err
nohup /opt/magepanel/install-chrome.sh > /tmp/hnc.log 2> /tmp/hnc.err &
