#!/usr/bin/env bash

launchctl unload -w /Library/LaunchDaemons/com.erincinci.magepanel.plist || true
launchctl load -w /Library/LaunchDaemons/com.erincinci.magepanel.plist

#launchctl submit \
#  -l com.hurpdurp.apps \
#  -o /var/logs/hellonode.info.log \
#  -e /var/logs/hellonode.err.log \
#  -- \
#  /usr/local/bin/node \
#  /opt/MagePanel/app.js
