#!/bin/bash

# Adjust file ownerships
echo "Changing ownership for source folders.."
chown -R root:staff /opt/MagePanel
chmod +x /opt/MagePanel/init-server.sh || true

# Get npm modules for project
echo "Download project's npm modules.."
mkdir -p /opt/MagePanel/logs || true
mkdir -p /opt/MagePanel/dbs || true
cd /opt/MagePanel
/usr/local/bin/npm install

# Unload & Load Daemon
echo "Unload & Load daemon.."
launchctl unload -w /Library/LaunchDaemons/com.erincinci.magepanel.plist || true
launchctl load -w /Library/LaunchDaemons/com.erincinci.magepanel.plist

#launchctl submit \
#  -l com.erincinci.magepanel \
#  -o /var/log/magepanel.info.log \
#  -e /var/log/magepanel.err.log \
#  -- \
#  /usr/local/bin/node \
#  /opt/MagePanel/app.js
