#!/bin/bash

# Variables
#if [[ ${SUDO_USER}  == '' ]]; then
#        INSTALL_USER=`whoami`
#else
#        INSTALL_USER=${SUDO_USER}
#fi
INSTALL_USER=`ls -l /dev/console | awk ' /dev/ {print $3}'`
PLIST_FILE=/Library/LaunchDaemons/com.erincinci.magepanel.plist
SOURCE_PATH=/opt/MagePanel

# Create folders & Adjust file/folder ownerships
echo "Creating & Changing ownership for source folders.."
mkdir -p ${SOURCE_PATH}/logs || true
mkdir /opt/logs || true
mkdir -p ${SOURCE_PATH}/dbs || true
chmod +x ${SOURCE_PATH}/init-server-mac.sh
chown -R ${INSTALL_USER}:staff ${SOURCE_PATH}
chown -R ${INSTALL_USER}:staff /opt/logs
chown root:wheel ${PLIST_FILE}

# Get npm modules for project
#echo "Download project's npm modules.."
#cd /opt/MagePanel
#/usr/local/bin/npm install

# Unload & Load Daemon
echo "Adjust daemon to user(${INSTALL_USER}) - Unload & Load daemon.."
sed -i '' s/root/${INSTALL_USER}/g ${PLIST_FILE}
launchctl unload -w ${PLIST_FILE} || true
launchctl load -w ${PLIST_FILE}
