#!/bin/bash
CURMAJOR=0
CURMINOR=10
CURPATCH=4
NEXTMAJOR=2
PACKAGE=node-v$CURMAJOR.$CURMINOR.$CURPATCH.pkg
MAJOR=`/usr/local/bin/node -e "require('util').print(process.version.replace('v', '').split('.')[0])" || true`
MINOR=`/usr/local/bin/node -e "require('util').print(process.version.replace('v', '').split('.')[1])" || true`
PATCH=`/usr/local/bin/node -e "require('util').print(process.version.replace('v', '').split('.')[2])" || true`

if [ $MAJOR -eq $CURMAJOR ]
then
  if [ $MINOR -lt $CURMINOR ]
  then
    # very old node, upgrade it
    echo "VERY OLD NODE, UPGRADE"
    installer -pkg $PACKAGE -target /
  elif [ $MINOR -eq $CURMINOR ]
  then
    if [ $PATCH -lt $CURPATCH ]
    then
      # old node, upgrade it
      echo "OLDER NODE, UPGRADE"
      installer -pkg $PACKAGE -target /
    else
      echo "RECENT NODE, NO CHANGE"
    fi
  fi
elif [ $MAJOR -lt $NEXTMAJOR ]
then
  echo "NEWER NODE, NO CHANGE"
elif [ $MAJOR -gte $NEXTMAJOR ]
then
  echo "WAY NEW NODE, MIGHT NOT WORK, BUT NO CHANGE"
else
  echo "NO NODE, INSTALL"
  installer -pkg $PACKAGE -target /
fi

ln -s /usr/local/bin/node /usr/bin/node || true
ln -s /usr/local/bin/npm /usr/bin/npm || true

# Install PHP-CLI if not exists
if ! type "php" > /dev/null; then
	echo "PHP-CLI not found on the system! Downloading & Installing.."
	curl -s http://php-osx.liip.ch/install.sh | bash -s 5.5
fi

# Install magallanes if not exists
if ! type "mage" > /dev/null; then
	echo "Magallanes not found on the system! Downloading & Installing.."
	cd /tmp
	wget http://download.magephp.com/magallanes.latest.tar.gz -O magallanes.tar.gz
	tar xfz magallanes.tar.gz
	cd magallanes
	bin/mage install --systemWide --installDir=/opt/magallanes
fi